apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployserver
  namespace: argocd
spec:
  source:
    path: kubernetes/1-deployment-service
    repoURL: https://github.com/chzgustavo/various.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
