apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    role: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      role: hello
      tier: web
  template:
    metadata:
      labels:
        role: hello
        tier: web
    spec:
      containers:
      - name: hello
        image: chzgustavo/node-helloworld:latest
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8000
