apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    env: test1
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1500m"
  priorityClassName: low-priority
