apiVersion: v1
kind: Pod
metadata:
  name: nginx3
  labels:
    env: test3
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "2000m"
  priorityClassName: high-priority-nonpreemptive
