apiVersion: v1
kind: Pod
metadata:
   name: config-pod-1
spec:
   containers:
     - name: test-container
       image: busybox
       command: [ "/bin/sh", "-c", "env" ]
       env:
         - name: SPECIAL_LEVEL_KEY
           valueFrom:              
             configMapKeyRef:
               name: special-config               
               key: SPECIAL_LEVEL                 
   restartPolicy: Never
