name: Go CI/CD

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
      
env:
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: Dockerfile

  tryvy:
    name: Build and scan with trivy
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: |
            chzgustavo/${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'chzgustavo/${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
  build:
    name: Continuos Integration
    runs-on: ubuntu-18.04
    needs: [lint, tryvy]
    steps:
      - name: Setting up Golang v1.14
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
      
      - name: Check out code
        uses: actions/checkout@v2

      - name: Testing
        run: |
          CGO_ENABLED=0 go test ./...
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            chzgustavo/${{ env.IMAGE_NAME }}:${{ github.sha }}
            
  deploy:
    name: Continuos Delivery
    runs-on: ubuntu-latest
    needs: [lint, tryvy, build]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Kustomize configuration
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Update kubernetes resource
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_IMAGE: ${{ github.event.repository.name }}
        run: |
         cd manifiestos-k8s
         kustomize edit set image gcr.io/google-samples/hello-app:2.0=$DOCKER_USERNAME/$DOCKER_IMAGE:$GITHUB_SHA
         cat kustomization.yaml
        
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Actualizacion de imagen"
      - name: Applying change in main branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
