apiVersion: v1
kind: Namespace
metadata:
  name: test1
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: test2
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

