apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: false
      allowEmpty: false
      selfHeal: false
  destination:
    namespace: test1
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: Kubernetes/00-deployment-service-pods/00-deployment-service
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
