---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v1
  labels:
    name: app-b
  namespace: app-b
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.test-argocd: semver:~v0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-v1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-v1
    spec:
      containers:
      - name: test-argocd
        image: chzgustavo/test-argocd:v0.0.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
