apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-ns.yaml
- 01-deployment.yaml
- 02-service.yaml
namespace: prueba
images:
- name: gcr.io/google-samples/hello-app:2.0
  newName: chzgustavo/hello-gitops
  newTag: latest

