apiVersion: v1
kind: Service
metadata:
  name: simon-service
spec:
  type: NodePort
  selector:
    app: simon
  ports:
  - port: 3001
    targetPort: 3001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simon
spec:
  selector:
    matchLabels:
      app: simon
  replicas: 2
  template:
    metadata:
      labels:
        app: simon
    spec:
      containers:
      - name: log-simon
        image: chzgustavo/log-simon:1.0
        #imagePullPolicy: Never
        ports:
        - containerPort: 3001
